// This file is auto-generated by @hey-api/openapi-ts

import type { GetCarsResponse } from './types.gen';

export const getCarsResponseTransformer = async (data: any): Promise<GetCarsResponse> => {
    data = data.map((item: any) => {
        item.updatedAt = new Date(item.updatedAt);
        return item;
    });
    return data;
};