// This file is auto-generated by @hey-api/openapi-ts

export type GetCarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cars';
};

export type GetCarsErrors = {
    /**
     * Error response
     */
    500: {
        /**
         * Code to handle on the frontend
         */
        error: 'UnknownError';
    };
};

export type GetCarsError = GetCarsErrors[keyof GetCarsErrors];

export type GetCarsResponses = {
    /**
     * List of cars
     */
    200: Array<{
        /**
         * Car name
         */
        name: string;
        /**
         * Make
         */
        make: string;
        /**
         * IQ. Tested in international studies
         */
        averageDriverIQ: number;
        /**
         * Last time the records was updated
         */
        updatedAt: Date;
    }>;
};

export type GetCarsResponse = GetCarsResponses[keyof GetCarsResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};