// This file is auto-generated by @hey-api/openapi-ts

/**
 * Car
 */
export type Car = {
    /**
     * Car name
     */
    name: string;
    /**
     * Make
     */
    make: string;
    /**
     * IQ. Tested in international studies
     */
    averageDriverIQ: number;
    /**
     * Last time the records was updated
     */
    updatedAt: Date;
};

/**
 * User
 */
export type User = {
    /**
     * Id
     */
    id: number;
    /**
     * Email
     */
    email: string;
    /**
     * User Name
     */
    name: string;
    /**
     * JWT token used on the frontend
     */
    jwt: string;
};

export type GetCarsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cars';
};

export type GetCarsErrors = {
    /**
     * Error with human readable explanation of what went wrong
     */
    400: {
        code: 'ActionError';
        humanReadable: string;
    };
    /**
     * Unauthorized Error
     */
    401: {
        code: 'Unauthorized';
    };
    /**
     * Unknown Error
     */
    500: {
        code: 'Unknown';
    };
};

export type GetCarsError = GetCarsErrors[keyof GetCarsErrors];

export type GetCarsResponses = {
    /**
     * List of cars
     */
    200: Array<Car>;
};

export type GetCarsResponse = GetCarsResponses[keyof GetCarsResponses];

export type PostAuthLoginData = {
    body?: {
        /**
         * User email
         */
        email: string;
        /**
         * User password
         */
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Error with human readable explanation of what went wrong
     */
    400: {
        code: 'ActionError';
        humanReadable: string;
    };
    /**
     * Unknown Error
     */
    500: {
        code: 'Unknown';
    };
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Good Response
     */
    200: User;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthRegisterData = {
    body?: {
        /**
         * User Name
         */
        name: string;
        /**
         * User email
         */
        email: string;
        /**
         * User password
         */
        password: string;
        /**
         * Confirmation of password
         */
        passwordConfirmation: string;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Error with human readable explanation of what went wrong
     */
    400: {
        code: 'ActionError';
        humanReadable: string;
    };
    /**
     * Unknown Error
     */
    500: {
        code: 'Unknown';
    };
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Good Response
     */
    200: User;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}/api` | (string & {});
};